routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/exam',function(){
// 	return view('/exam.create');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/registerstudent','StudentController@studentdetails')->name('submit');
//Route::post('/updatestudent','StudentController@updatedetails')->name('updatedetails');
Route::post('/update/{id}','StudentController@update')->name('update');
Route::resource('examinfo','ExaminfoController');
Route::resource('makequestion' , 'QuestionController');
Route::resource('student','StudentController');
Route::resource('answer','AnswerController');
Route::resource('result' , 'ResultController');

resources/views/home.blade.php
@extends('layouts.app')
</<!DOCTYPE html>
<html>
<head>
 
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}
 
input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}
 
input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}
 
input[type=submit]:hover {
  background-color: #45a049;
}
 
.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
</head>
<body>
<div class="links">
<a class="btn btn-primary"  href="{{route('examinfo.create')}}">Create Exam</a>

</div>

<div class="container">
 
 <form method="POST" action="{{ route('submit') }}">

     {{ csrf_field() }}

    <div>
       <label >Student Name</label>
       <input type="text" name="student_id" placeholder="student Name" required>

   </div>
   <div>
         <label >Password</label>
         <input type="password" name="password" placeholder="Password" required>

   </div>
   <div>

         <input type="submit" value="register">

   </div>

 </form>  

</div> 
</body>
</html>