routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/exam',function(){
// 	return view('/exam.create');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/registerstudent','StudentController@studentdetails')->name('submit');
//Route::post('/updatestudent','StudentController@updatedetails')->name('updatedetails');
Route::post('/update/{id}','StudentController@update')->name('update');
Route::resource('examinfo','ExaminfoController');
Route::resource('makequestion' , 'QuestionController');
Route::resource('student','StudentController');
Route::resource('answer','AnswerController');
Route::resource('result' , 'ResultController');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    //
    protected $fillable = [
        'stu_id', 'question', 'given_answer','true_answer',
    ];
}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Answer;
use App\Student;

class AnswerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   return("test");die();
        //
        if ($request->ajax()) {
            $answer=Answer::create([
                'stu_id' => $request->input('student_id'),
                'question' => $request->input('question'),
                'given_answer' => $request->input('answer'),
                'true_answer' => $request->input('true_answer')

            ]);return "success";
            if ($request->input('answer')==$request->input('true_answer')) {
                $insert=Student::where('id',$request->input('student_id'))->increment('score');
            }
            return response($answer);
        }else{
            return "ajax not done";
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/answer/show.blade.php
@extends('layouts.app')

@section('script')

<!-- script for time limitation of exam -->
<script type="text/javascript">
var timeoutHandle;
function countdown(minutes) {
    var seconds = 60;
    var mins = minutes
    function tick() {
        var counter = document.getElementById("timer");
        var current_minutes = mins-1
        seconds--;
        counter.innerHTML =
        current_minutes.toString() + ":" + (seconds < 10 ? "0" : "") + String(seconds);
        if( seconds > 0 ) {
            timeoutHandle=setTimeout(tick, 1000);
        } else {

            if(mins > 1){

               // countdown(mins-1);   never reach “00″ issue solved:Contributed by Victor Streithorst
               setTimeout(function () { countdown(mins - 1); }, 1000);

            }
        }
    }
    tick();
}

countdown('<?php echo $time; ?>');

</script>

<!-- script for disable url -->
<script type="text/javascript">
    var time= '<?php echo $time; ?>';
    var realtime = time*60000;
    setTimeout(function () {
        alert('Time Out');
        window.location.href= '/';},
   realtime);

    
</script>

@endsection




@section('content')
<body style="background-color: darkseagreen">
    <div>
        <nav class="col-lg-1 pull-right">
          <div class="sidebar-nav-fixed affix">
            <h1><b>Time <span id="timer" style="color: red">0.00</span></b></h1><br>
          </div>
        </nav>
        <h1 class="col-lg-offset-4" style="color: red;"><span style="background-color:seagreen;color: white;border-radius: 5px"><b>  Examination on {{$course}}  </b></span></h1>
        <div class="col-md-6 col-lg-6 col-sm-6 col-lg-offset-3" style="background-color: white">
            
        @foreach($questions as $question)
            <div class="col-md-6 col-lg-8 col-sm-6 col-lg-offset-2">
                <form method="post" action="{{route('answer.store')}}" class="ansform">
                	{{ csrf_field() }}

                    <h3>{{$question->question}} ?</h3>
                    <div class="col-lg-offset-1">
                        <input type="hidden" name="question" value="{{$question->question}}">
                        <input type="hidden" name="student_id" value="{{$student_id}}">
                        <input type="hidden" name="true_answer" value="{{$question->answer}}">
                        <input name="answer" value="{{$question->choice1}}" type="radio"> {{$question->choice1}} <br>
                        <input name="answer" value="{{$question->choice2}}" type="radio">{{$question->choice2}}<br>
                        <input name="answer" value="{{$question->choice3}}" type="radio">{{$question->choice3}}<br>
                        <input name="answer" value="{{$question->choice4}}" type="radio">{{$question->choice4}}<br>
                        <input type="submit" name="submit" value="submit" class="btn btn-primary" id="submitbtn">
                    </div>
                 </form>
            </div>
         @endforeach

        </div>
    </div>
   
</body>




@endsection

	 