routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/exam',function(){
// 	return view('/exam.create');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/registerstudent','StudentController@studentdetails')->name('submit');
//Route::post('/updatestudent','StudentController@updatedetails')->name('updatedetails');
Route::post('/update/{id}','StudentController@update')->name('update');
Route::resource('examinfo','ExaminfoController');
Route::resource('makequestion' , 'QuestionController');
Route::resource('student','StudentController');
Route::resource('answer','AnswerController');
Route::resource('result' , 'ResultController');

resources/views/makequestion/create.blade.php
@extends('layouts.app')

@section('content')
<h2 style="text-align: center;"><b>Create Questions System will redirect you when set is full</b></h2>
<form method="post" action="{{route('makequestion.store')}}">
	{{ csrf_field() }}
    
		<div class="col-md-6 col-lg-6 col-sm-6 col-lg-offset-3">
		  <div class="form-group">
		    <label class="col-form-label" for="formGroupExampleInput">Question</label>
		    <input type="text" name="question" class="form-control " id="formGroupExampleInput" required>
		  </div>
		  <div class="form-group">
		    <label class="col-form-label" for="formGroupExampleInput2">option 1</label>
		    <input type="text" name="option1" class="form-control" id="formGroupExampleInput2" required>
		  </div>
		  <div class="form-group">
		    <label class="col-form-label" for="formGroupExampleInput2">Option 2</label>
		    <input type="text" name="option2" class="form-control" id="formGroupExampleInput2" required>
		  </div>
		  <div class="form-group">
		    <label class="col-form-label" for="formGroupExampleInput2">Option 3</label>
		    <input type="text" name="option3" class="form-control" id="formGroupExampleInput2" required>
		  </div>
		  <div class="form-group">
		    <label class="col-form-label" for="formGroupExampleInput2">Option 4</label>
		    <input type="text" name="option4" class="form-control" id="formGroupExampleInput2" required>
		  </div>
		  <div class="form-group">
		    <label class="col-form-label" for="formGroupExampleInput2">Answer</label>
		    <input type="text" name="answer" class="form-control" id="formGroupExampleInput2" required>
		  </div>
		  <div class="form-group">
		    <label class="col-form-label" for="formGroupExampleInput2">Quiz ID</label>
		    <input type="hidden" name="quizid" class="form-control" id="formGroupExampleInput2" value="{{$examinfo->id}}" readonly>
		  </div>
		  <button type="Submit" class="btn btn-success btn-block">Submit</button>
		</div>

</form>

    @endsection

resources/views/makequestion/edit.blade.php
@extends('layouts.app')

@section('script')
<script type="text/javascript">

</script>
@endsection

@section('content')
<body style="background-color: #63e9ab">
    <div class="container">
        <h2 style="text-align: center;">Review Question</strong></h2>
  		@foreach($questions as $question)
            <div class="">
                <form method="get" action="/makequestion/{{$question->id}}/edit" class="ansform">
                	{{ csrf_field() }}
                    <div class="">
                    	<!-- <p>{{$question->id}}</p> -->
                    	<input type="hidden" name="questionId" id="question" value="{{$question->id}}">

                        <input type="hidden" name="true_answer"  value="{{$question->answer}}">

                        <table class="table bg-success">
                          <tbody>
                            <div class="form-group">
                            <tr class="danger">
                              <td><strong>Question : </strong></td>
                              <td><input type="text" class="form-control" name="question" value="{{$question->question}}" readonly></td>

                            </tr>
                            </div>

                            <div class="form-group">
                            <tr class="bg-success">
                              <td><strong>Choice1 : </strong></td>
                              <td><input name="choice1" class="form-control"  value="{{$question->choice1}}" type="text" readonly></td>
                            </tr>
                          </div>

                          <div class="form-group">
                            <tr class="danger">
                              <td><strong>Choice2 : </strong></td>
                              <td><input name="choice2" class="form-control" value="{{$question->choice2}}" type="text" readonly></td>
                            </tr>
                          </div>

                          <div class="form-group">
                            <tr class="bg-success">
                              <td><strong>Choice3 : </strong></td>
                              <td><input name="choice3" class="form-control" value="{{$question->choice3}}" type="text" readonly></td>
                            </tr>
                          </div>

                          <div class="form-group">
                            <tr class="warning">
                              <td><strong>Choice4 : </strong></td>
                              <td><input name="choice4" class="form-control" value="{{$question->choice4}}" type="text" readonly></td>
                            </tr>
                          </div>

                          <div class="form-group">
                            <tr class="bg-success">
                              <td><strong>Answer : </strong></td>
                              <td><input name="answer" class="form-control" value="{{$question->answer}}" type="text" readonly></td>
                            </tr>
                          </div>
                          </tbody>
                        </table>
                    </div>
                    <button type="submit" name="submitFromEditPage" class="btn btn-warning btn-md edit_data  btn-lg align-center btn-block">Edit</button>
                 </form>
            </div><br>
         @endforeach






<a href="/"><button type="button" name="ReviewDone" class="btn btn-primary btn-block">Review Done</button></a><br><br>

</body>




@endsection

resources/views/makequestion/editone.blade.php
@extends('layouts.app')

@section('content')

@foreach($questions as $question)
	
<body style="background-color: #63e9ab">
	<div class="">
<form  method="post" action="{{route('makequestion.update', [$question->id])}}">
	{{ csrf_field() }}
	<input type="hidden" name="_method" value="put">
	<input type="hidden" name="quiz_id" value="{{$question->quiz_id}}">
		<div class="col-md-8 col-md-offset-2">
	 <table class="table col-lg-6">
                  <tbody>
                    <div class="form-group">
                    <tr class="danger">
                      <td><strong>Question : </strong></td>
                      <td><input type="text" class="form-control" name="question" value="{{$question->question}}" required></td>
                      
                    </tr>

                    </div>  

                    <div class="form-group">    
                    <tr class="bg-success">
                      <td><strong>Choice1 : </strong></td>
                      <td><input name="choice1" class="form-control"  value="{{$question->choice1}}" type="text" required></td>
                    </tr>
                  </div>

                  <div class="form-group">
                    <tr class="danger">
                      <td><strong>Choice2 : </strong></td>
                      <td><input name="choice2" class="form-control" value="{{$question->choice2}}" type="text" required></td>
                    </tr>
                  </div>

                  <div class="form-group">
                    <tr class="bg-success">
                      <td><strong>Choice3 : </strong></td>
                      <td><input name="choice3" class="form-control" value="{{$question->choice3}}" type="text" required></td>
                    </tr>
                  </div>

                  <div class="form-group">
                    <tr class="danger">
                      <td><strong>Choice4 : </strong></td>
                      <td><input name="choice4" class="form-control" value="{{$question->choice4}}" type="text" required></td>
                    </tr>
                  </div>

                  <div class="form-group">
                    <tr class="bg-success">
                      <td><strong>Answer : </strong></td>
                      <td><input name="answer" class="form-control" value="{{$question->answer}}" type="text" required></td>
                    </tr>
                  </div>
                  </tbody>
                </table>
                <input type="submit" class="btn btn-success btn-block" name="update" value="update">
            </div>
         
</form>
</div>
</body>
@endforeach
@endsection

resources/views/makequestion/index.blade.php
@extends('layouts.app')

@section('content')

 <div class="col-md-6 col-lg-6 col-sm-6 col-lg-offset-4" style="width:550px;font-weight:bold;">
	 <h2 style="color: green">Your Question Set is complete</h2>
	  <!-- Trigger the modal with a button -->
	  <h2>Please Remember your Exam Code : <span style="color: red;font-size: 40px; font-weight: bold;">{{$uniqueid}}</span></h2>
	  <a href="/"><button type="button" class="btn btn-info btn-lg btn-block"> Back To Home </button></a><br>
	  <form action="/makequestion/{{$uniqueid}}/edit" method="get">
	  	{{ csrf_field() }}
	  	<input type="hidden" name="uniqueid" value="{{$uniqueid}}">
	  	<button type="submit" class="btn btn-info btn-lg btn-block">Review Questions</button>
	  </form>
  </div>

 @endsection